### ISSUE TITLE
Floats do not round as expected.

### ISSUE THREAD

**Issue by ghost** [vimt/MaxMind-DB-Writer-python#1]
Rounded floats display to 15 decimal places.
For example even after rounding `52.3456` to 2dp, the generated database resolves to `52.349998474121094` .

![Capture2](https://user-images.githubusercontent.com/44903737/103140155-32438500-46db-11eb-8329-a0821e1e3cff.PNG)
![Capture1](https://user-images.githubusercontent.com/44903737/103140157-366fa280-46db-11eb-9a5c-78c771edb9cb.PNG)

**Comment by ShadoKima** [comment]
The issue turned out to be an issue in my MMDB parser.
![d7e112585af02e7e96ddbd5cfe3fe34c](https://user-images.githubusercontent.com/44903737/103142701-b576d200-46ff-11eb-8ece-8caecfd6e2e7.jpg)

**Comment by vimt** [comment]
as mention in [MaxMind DB File Format Specification](http://maxmind.github.io/MaxMind-DB/)
float has two format: float with 4 bytes and double with 8 bytes. (`mmdb_writer` use float by default.)

IEEE-754 double/float format will lose precision when serialization.

if you want build python float as double format. you can do this before writer.to_db_file
```python
import mmdb_writer
mmdb_writer.Encoder._python_type_id[float] = 3
```
